

GET http://localhost:8080/api/colors

###

GET http://localhost:8080/api/categories
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkb2Rzd29ydGgiLCJkaXNwbGF5X25hbWUiOiJBbm5lIERvZHN3b3J0aCIsInVzZXJfa2luZCI6ImVtcGxveWVlIiwicm9sZXMiOlsidXNlciJdLCJpc19hY2Nlc3MiOnRydWUsImlzX3JlZnJlc2giOmZhbHNlLCJleHAiOjE2MDY3NjM1MTZ9.xsg3pyu-KyvxtVK1nrD5xaQuFXRhjjkWCccWLTNZMOk

###

GET http://localhost:8080/api/employees
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFmdWxsZXIiLCJkaXNwbGF5X25hbWUiOiJBbmRyZXcgRnVsbGVyIiwidXNlcl9raW5kIjoiZW1wbG95ZWUiLCJyb2xlcyI6WyJ1c2VyIiwiYWRtaW4iXSwiaXNfYWNjZXNzIjp0cnVlLCJpc19yZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjA2NzY4NjcwfQ.S-6pIbNBTfwPlU5biNyl6ocMFcc8NLG59nkiselDPuA